/**
 * Property matrix for react-two.js components against Two.js v0.8.23.
 *
 * This module defines every exported component, its underlying Two.js class,
 * all supported scene-relevant declarative properties, and intentional omissions
 * (such as internal renderer state or computed properties) with explanations.
 */

export const SUPPORTED_TWO_VERSION = '0.8.23' as const;

export type OmissionCategory =
  | 'read-only'
  | 'renderer-internal'
  | 'managed-by-react'
  | 'imperative-method';

export interface PropertyOmission {
  readonly property: string;
  readonly reason: OmissionCategory;
  readonly description: string;
}

export interface ComponentPropertyMatrix {
  readonly component: string;
  readonly twoClass: string;
  readonly supportedProps: readonly string[];
  readonly omittedProps: readonly PropertyOmission[];
}

const COMMON_SHAPE_OMISSIONS: readonly PropertyOmission[] = [
  {
    property: 'worldMatrix',
    reason: 'read-only',
    description:
      'Computed world-space transformation matrix generated during rendering. Read via ref.current.worldMatrix.',
  },
  {
    property: 'renderer',
    reason: 'renderer-internal',
    description:
      'Internal renderer state and DOM elements (e.g. renderer.elem for SVG). Access imperatively via ref.current.renderer.',
  },
  {
    property: 'parent',
    reason: 'managed-by-react',
    description:
      'Hierarchy is managed declaratively by the React component tree.',
  },
  {
    property: 'clone',
    reason: 'imperative-method',
    description: 'Method to clone Two.js object. Call on ref.current.',
  },
  {
    property: 'copy',
    reason: 'imperative-method',
    description: 'Method to copy properties from another Two.js object.',
  },
  {
    property: 'addTo',
    reason: 'imperative-method',
    description: 'Scenegraph modification managed declaratively by React.',
  },
  {
    property: 'remove',
    reason: 'imperative-method',
    description: 'Scenegraph modification managed declaratively by React.',
  },
];

const COMMON_PATH_OMISSIONS: readonly PropertyOmission[] = [
  ...COMMON_SHAPE_OMISSIONS,
  {
    property: 'length',
    reason: 'read-only',
    description:
      'Computed arc length of path vertices. Read via ref.current.length.',
  },
  {
    property: 'subdivide',
    reason: 'imperative-method',
    description: 'Imperative vertex subdivision algorithm.',
  },
  {
    property: 'plot',
    reason: 'imperative-method',
    description: 'Method to recalculate path curves from anchors.',
  },
];

export const PROPERTY_MATRIX: Record<string, ComponentPropertyMatrix> = {
  Group: {
    component: 'Group',
    twoClass: 'Two.Group',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'cap',
      'join',
      'miter',
      'closed',
      'curved',
      'automatic',
      'opacity',
      'visible',
      'mask',
      'beginning',
      'ending',
      'strokeAttenuation',
      'x',
      'y',
    ],
    omittedProps: [
      ...COMMON_SHAPE_OMISSIONS,
      {
        property: 'length',
        reason: 'read-only',
        description:
          'Computed sum of distances between all children lengths. Read via ref.current.length.',
      },
      {
        property: 'children',
        reason: 'managed-by-react',
        description:
          'Children are managed declaratively through React JSX children rather than direct prop assignment.',
      },
      {
        property: 'additions',
        reason: 'renderer-internal',
        description:
          'Internal renderer list of children to be appended. Maintained by Two.js scenegraph.',
      },
      {
        property: 'subtractions',
        reason: 'renderer-internal',
        description:
          'Internal renderer list of children to be removed. Maintained by Two.js scenegraph.',
      },
    ],
  },

  SVG: {
    component: 'SVG',
    twoClass: 'Two.Group',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'cap',
      'join',
      'miter',
      'closed',
      'curved',
      'automatic',
      'opacity',
      'visible',
      'mask',
      'beginning',
      'ending',
      'strokeAttenuation',
      'src',
      'content',
      'shallow',
      'onLoad',
      'onError',
      'x',
      'y',
    ],
    omittedProps: [
      ...COMMON_SHAPE_OMISSIONS,
      {
        property: 'children',
        reason: 'managed-by-react',
        description:
          'Parsed SVG children are populated asynchronously into the group by two.load().',
      },
    ],
  },

  Path: {
    component: 'Path',
    twoClass: 'Two.Path',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'opacity',
      'visible',
      'cap',
      'join',
      'miter',
      'closed',
      'curved',
      'automatic',
      'beginning',
      'ending',
      'dashes',
      'vertices',
      'mask',
      'clip',
      'strokeAttenuation',
      'manual',
      'x',
      'y',
    ],
    omittedProps: COMMON_PATH_OMISSIONS,
  },

  Rectangle: {
    component: 'Rectangle',
    twoClass: 'Two.Rectangle',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'opacity',
      'visible',
      'cap',
      'join',
      'miter',
      'closed',
      'curved',
      'automatic',
      'beginning',
      'ending',
      'dashes',
      'vertices',
      'mask',
      'clip',
      'strokeAttenuation',
      'width',
      'height',
      'origin',
      'x',
      'y',
    ],
    omittedProps: COMMON_PATH_OMISSIONS,
  },

  Circle: {
    component: 'Circle',
    twoClass: 'Two.Circle',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'opacity',
      'visible',
      'cap',
      'join',
      'miter',
      'closed',
      'curved',
      'automatic',
      'beginning',
      'ending',
      'dashes',
      'vertices',
      'mask',
      'clip',
      'strokeAttenuation',
      'radius',
      'resolution',
      'x',
      'y',
    ],
    omittedProps: COMMON_PATH_OMISSIONS,
  },

  Ellipse: {
    component: 'Ellipse',
    twoClass: 'Two.Ellipse',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'opacity',
      'visible',
      'cap',
      'join',
      'miter',
      'closed',
      'curved',
      'automatic',
      'beginning',
      'ending',
      'dashes',
      'vertices',
      'mask',
      'clip',
      'strokeAttenuation',
      'width',
      'height',
      'resolution',
      'x',
      'y',
    ],
    omittedProps: COMMON_PATH_OMISSIONS,
  },

  Line: {
    component: 'Line',
    twoClass: 'Two.Line',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'opacity',
      'visible',
      'cap',
      'join',
      'miter',
      'closed',
      'curved',
      'automatic',
      'beginning',
      'ending',
      'dashes',
      'vertices',
      'mask',
      'clip',
      'strokeAttenuation',
      'left',
      'right',
      'x1',
      'y1',
      'x2',
      'y2',
    ],
    omittedProps: COMMON_PATH_OMISSIONS,
  },

  Polygon: {
    component: 'Polygon',
    twoClass: 'Two.Polygon',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'opacity',
      'visible',
      'cap',
      'join',
      'miter',
      'closed',
      'curved',
      'automatic',
      'beginning',
      'ending',
      'dashes',
      'vertices',
      'mask',
      'clip',
      'strokeAttenuation',
      'width',
      'height',
      'sides',
      'radius',
      'x',
      'y',
    ],
    omittedProps: COMMON_PATH_OMISSIONS,
  },

  RoundedRectangle: {
    component: 'RoundedRectangle',
    twoClass: 'Two.RoundedRectangle',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'opacity',
      'visible',
      'cap',
      'join',
      'miter',
      'closed',
      'curved',
      'automatic',
      'beginning',
      'ending',
      'dashes',
      'vertices',
      'mask',
      'clip',
      'strokeAttenuation',
      'width',
      'height',
      'radius',
      'x',
      'y',
    ],
    omittedProps: COMMON_PATH_OMISSIONS,
  },

  Star: {
    component: 'Star',
    twoClass: 'Two.Star',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'opacity',
      'visible',
      'cap',
      'join',
      'miter',
      'closed',
      'curved',
      'automatic',
      'beginning',
      'ending',
      'dashes',
      'vertices',
      'mask',
      'clip',
      'strokeAttenuation',
      'innerRadius',
      'outerRadius',
      'sides',
      'x',
      'y',
    ],
    omittedProps: COMMON_PATH_OMISSIONS,
  },

  ArcSegment: {
    component: 'ArcSegment',
    twoClass: 'Two.ArcSegment',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'opacity',
      'visible',
      'cap',
      'join',
      'miter',
      'closed',
      'curved',
      'automatic',
      'beginning',
      'ending',
      'dashes',
      'vertices',
      'mask',
      'clip',
      'strokeAttenuation',
      'startAngle',
      'endAngle',
      'innerRadius',
      'outerRadius',
      'resolution',
      'x',
      'y',
    ],
    omittedProps: COMMON_PATH_OMISSIONS,
  },

  Points: {
    component: 'Points',
    twoClass: 'Two.Points',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'opacity',
      'visible',
      'size',
      'sizeAttenuation',
      'beginning',
      'ending',
      'dashes',
      'vertices',
      'strokeAttenuation',
      'x',
      'y',
    ],
    omittedProps: [
      ...COMMON_SHAPE_OMISSIONS,
      {
        property: 'mask',
        reason: 'read-only',
        description:
          'Two.Points does not implement mask in Two.js. Wrap in a Two.Group with mask instead.',
      },
      {
        property: 'clip',
        reason: 'read-only',
        description: 'Two.Points does not implement clip in Two.js.',
      },
      {
        property: 'length',
        reason: 'read-only',
        description:
          'Number of vertices in the points collection. Read via ref.current.length.',
      },
    ],
  },

  Text: {
    component: 'Text',
    twoClass: 'Two.Text',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'value',
      'family',
      'size',
      'leading',
      'alignment',
      'linewidth',
      'style',
      'weight',
      'decoration',
      'direction',
      'baseline',
      'opacity',
      'visible',
      'fill',
      'stroke',
      'dashes',
      'mask',
      'clip',
      'strokeAttenuation',
      'x',
      'y',
    ],
    omittedProps: COMMON_SHAPE_OMISSIONS,
  },

  Image: {
    component: 'Image',
    twoClass: 'Two.Image',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'opacity',
      'visible',
      'cap',
      'join',
      'miter',
      'closed',
      'curved',
      'automatic',
      'beginning',
      'ending',
      'dashes',
      'vertices',
      'mask',
      'clip',
      'strokeAttenuation',
      'width',
      'height',
      'origin',
      'mode',
      'texture',
      'src',
      'x',
      'y',
    ],
    omittedProps: COMMON_PATH_OMISSIONS,
  },

  Sprite: {
    component: 'Sprite',
    twoClass: 'Two.Sprite',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'opacity',
      'visible',
      'cap',
      'join',
      'miter',
      'closed',
      'curved',
      'automatic',
      'beginning',
      'ending',
      'dashes',
      'vertices',
      'mask',
      'clip',
      'strokeAttenuation',
      'width',
      'height',
      'origin',
      'texture',
      'columns',
      'rows',
      'frameRate',
      'index',
      'firstFrame',
      'lastFrame',
      'loop',
      'src',
      'autoPlay',
      'x',
      'y',
    ],
    omittedProps: [
      ...COMMON_PATH_OMISSIONS,
      {
        property: 'play',
        reason: 'imperative-method',
        description:
          'Playback method. Available declaratively via autoPlay prop or ref.current.play().',
      },
      {
        property: 'pause',
        reason: 'imperative-method',
        description:
          'Playback method. Available declaratively via autoPlay={false} or ref.current.pause().',
      },
      {
        property: 'stop',
        reason: 'imperative-method',
        description: 'Playback method. Call ref.current.stop().',
      },
    ],
  },

  ImageSequence: {
    component: 'ImageSequence',
    twoClass: 'Two.ImageSequence',
    supportedProps: [
      'id',
      'className',
      'position',
      'translation',
      'rotation',
      'scale',
      'skewX',
      'skewY',
      'matrix',
      'fill',
      'stroke',
      'linewidth',
      'opacity',
      'visible',
      'cap',
      'join',
      'miter',
      'closed',
      'curved',
      'automatic',
      'beginning',
      'ending',
      'dashes',
      'vertices',
      'mask',
      'clip',
      'strokeAttenuation',
      'width',
      'height',
      'origin',
      'textures',
      'frameRate',
      'index',
      'firstFrame',
      'lastFrame',
      'loop',
      'src',
      'autoPlay',
      'x',
      'y',
    ],
    omittedProps: [
      ...COMMON_PATH_OMISSIONS,
      {
        property: 'play',
        reason: 'imperative-method',
        description:
          'Playback method. Available declaratively via autoPlay prop or ref.current.play().',
      },
      {
        property: 'pause',
        reason: 'imperative-method',
        description:
          'Playback method. Available declaratively via autoPlay={false} or ref.current.pause().',
      },
      {
        property: 'stop',
        reason: 'imperative-method',
        description: 'Playback method. Call ref.current.stop().',
      },
    ],
  },

  LinearGradient: {
    component: 'LinearGradient',
    twoClass: 'Two.LinearGradient',
    supportedProps: [
      'id',
      'className',
      'spread',
      'units',
      'stops',
      'left',
      'right',
      'x1',
      'y1',
      'x2',
      'y2',
    ],
    omittedProps: [
      {
        property: 'renderer',
        reason: 'renderer-internal',
        description:
          'Internal renderer state and DOM element (e.g. SVGLinearGradientElement). Access via ref.current.renderer.',
      },
    ],
  },

  RadialGradient: {
    component: 'RadialGradient',
    twoClass: 'Two.RadialGradient',
    supportedProps: [
      'id',
      'className',
      'spread',
      'units',
      'stops',
      'center',
      'radius',
      'focal',
      'x',
      'y',
      'focalX',
      'focalY',
    ],
    omittedProps: [
      {
        property: 'renderer',
        reason: 'renderer-internal',
        description:
          'Internal renderer state and DOM element (e.g. SVGRadialGradientElement). Access via ref.current.renderer.',
      },
    ],
  },

  Texture: {
    component: 'Texture',
    twoClass: 'Two.Texture',
    supportedProps: [
      'id',
      'className',
      'src',
      'loaded',
      'repeat',
      'scale',
      'offset',
      'image',
    ],
    omittedProps: [
      {
        property: 'renderer',
        reason: 'renderer-internal',
        description:
          'Internal renderer state and DOM pattern/canvas. Access via ref.current.renderer.',
      },
    ],
  },
};
